### ISSUE TITLE
AMQJS0004E Ping timed out.

### ISSUE THREAD

**Issue by hobbysistemas** [rh389/react-native-paho-mqtt#4]
After running app in android device or simulator, it send the first ping req and the ping resp does not arrives to the app. the app sends another ping req and the mosquitto sends the ping resp but it does not arrives and the alert AMQJS0004E Ping timed out is shown.
Using mosquitto, with authentication, linux ubuntu 16, react native through websockets on port 8083

I tried to use the same mosquitto instance directly from browser, using hivemq mqtt web client and everything works, even from the linux command line...

It is clear on mosquitto log that it answers with PING RESP but this never rechas the react native app end point.

Any help?

Thanks 

Imo

**Comment by definitelycarter** [comment]
Facing the same issue here.

**Comment by AdamChrist** [comment]
+1

**Comment by rh389** [comment]
Thanks all - I'm looking into this now. See also discussion at https://github.com/eclipse/paho.mqtt.javascript/issues/106

**Comment by rh389** [comment]
I believe this is fixed by https://github.com/rh389/react-native-paho-mqtt/commit/8185b64928c5d0f87111b1e99dfbc423163d270d, released as [0.1.0](https://www.npmjs.com/package/react-native-paho-mqtt) (CC @MattyK14). Let me know how you get on!

**Comment by MattyK14** [comment]
Seems to be working well on both iOS & Android!
