### ISSUE TITLE
Incompatible with React Native 0.46 on Android

### ISSUE THREAD

**Issue by rh389** [rh389/react-native-paho-mqtt#6]
As a reminder to myself - this lib is incompatible with RN 0.46 up to and including 0.47-rc.4, due to binary websockets being broken, until https://github.com/facebook/react-native/commit/7e29b1fc7711a285765f021be3e83a981b066435 is released.

Edit: Fix cherry picked into 0.47-rc.5.

**Comment by ianjwood** [comment]
Confirmed as working with 0.47.1
