### ISSUE TITLE
How to disable console logs / trace?

### ISSUE THREAD

**Issue by JulianKingman** [rh389/react-native-paho-mqtt#8]
I get a console log for ever message and action the MQTT client takes, is there a way to disable them? I tried using the `traceFunction` option and the `trace` option in the client constructor, but that didn't seem to do anything. I'd expect something like "debug: false"

**Comment by robhogan** [comment]
There shouldn't be any output unless you've explicitly set a trace function (eg with `client._client.traceFunction = console.log` or with `client.trace = console.log`). Are you sure you haven't got some stray debug code somewhere?

**Comment by JulianKingman** [comment]
Arg, oh my gosh. No, I'm not sure 😳 

I had this hidden in my code, I totally forgot I added it: `this.client._client.traceFunction = trace => console.log(trace.message);`

**Comment by robhogan** [comment]
That [looks familiar](https://github.com/rh389/react-native-paho-mqtt/issues/5#issuecomment-316664086)! Glad it's not a problem.
